---
# Active Directory Configuration
domain_name: "lab.local"
domain_netbios_name: "LAB"
safe_mode_password: "SafeMode123!@#"
forest_mode: "WinThreshold"
domain_mode: "WinThreshold"

forward_zone: "lab.local"
reverse_zone: "65.100.in-addr.arpa"

dc_hostname: "AX6740-DC01"
dc_ip_address: "100.65.7.12"
ansible_host_hostname: "AX6740-UBUNTU"
ansible_host_ip_address: "100.65.2.231"

# Network Configuration
dns_forwarder: "8.8.8.8"

# Domain Admins
domain_admins:
  - "admin.user"

# Organizational Units
organizational_units:
  - name: "Users"
    path: "OU=Users,DC=lab,DC=local"
  - name: "Computers"
    path: "OU=Computers,DC=lab,DC=local"
  - name: "Servers"
    path: "OU=Servers,DC=lab,DC=local"
  - name: "Service Accounts"
    path: "OU=Service Accounts,DC=lab,DC=local"

# Standard Users
# ===============================================================
# Format of
# domain_users:
# - username: ...
#   password: ...
#   firstname: ...
#   lastname: ...
#   ou: "OU=Users, DC=lab, DC=local"
#   groups:
#     - "Domain Admins"      (whatever group is needed)
# ===============================================================
domain_users:
  - username: "admin.user"
    password: "studentTest!"
    firstname: "Admin"
    lastname: "User"
    ou: "OU=Users,DC=lab,DC=local"
    groups:
      - "Domain Admins"
