---
# ======================================================================================
# Creates security vulnerabilities onto Domain and explicity for the Domain Controllers
# 
# Create Vulnerable GPO settings
# - Disable SMB Signing
# - Disable LDAP Signing
#
# Create users meant to be exploited
# ======================================================================================

vulnerable_users:
  - username: "svc_sql"
    password: "studentBad!"
    spn: "MSSQLSvc/sql01.lab.local:1433"
    description: "SQL Service Account"
    ou: "OU=Service Accounts,DC=lab,DC=local"
  - username: "svc_web"
    password: "studentBad!"
    spn: "HTTP/web01.lab.local"
    description: "Web Service Account"
    ou: "OU=Service Accounts,DC=lab,DC=local"

# Weak GPO settings
# vulnerable_gpo_settings:
#   - name: "Disable SMB Signing"
#     setting: "Microsoft.Policies.SMBSigning"
#     value: "Disabled"
#   - name: "Disable LDAP Signing"
#     setting: "Microsoft.Policies.LDAPSigning"
#     value: "None"

# Weak GPO Settings
vulnerable_gpo_settings:
  - name: "Disable SMB Signing"
    key: 'HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters'
    value_name: "SMB1"
    type: "DWORD"
    value: 0
  - name: "Disable LDAP Signing"
    key: 'HKLM\SYSTEM\CurrentControlSet\Services\NTDS\Parameters'
    value_name: "LDAPServerIntegrity"
    type: "DWORD"
    value: 0
  - name: "Disable SMB2 Signing"
    key: 'HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters'
    value_name: "SMB2"
    type: "DWORD"
    value: 0
  - name: "Enable LLMNR"
    key: 'HKLM\SYSTEM\CurrentControlSet\Services\DNSClient\Parameters'
    value_name: "EnableMulticast"
    type: "DWORD"
    value: 1

# Delegation issues
unconstrained_delegation_computers:
  - "WEB01"
  - "APP01"
