---
ad_domain_name: "scp.com"
ad_netbios_name: "SCP"
ad_safe_mode_password: "DONOTTOUCH!!!@123$"

servers:
  - name: "SCP-DC01"
    ip_address: "10.10.10.21"
  - name: "SCP-SMB01"
    ip_address: "10.10.10.22"
  - name: "SCP-FTP01"
    ip_address: "10.10.10.101"
  - name: "SCP-REDIS01"
    ip_address: "10.10.10.102"
  - name: "SCP-DATABASE01"
    ip_address: "10.10.10.103"
  - name: "SCP-AMAZIN01"
    ip_address: "10.10.10.104"
  - name: "SCP-SAMBA01"
    ip_address: "10.10.10.105"
