---
ad_domain_name: "scp.com"
ad_netbios_name: "SCP"
ad_safe_mode_password: "DONOTTOUCH!!!"

servers:
  - name: "SCP-DC01"
    ip_address: "1.1.1.1"
  - name: "SCP-SMB01"
    ip_address: "1.1.1.2"
  - name: "SCP-SFTP01"
    ip_address: "1.1.1.3"
