# Ansible Hosts File
# Tells Ansible how to handle what servers are our domain controllers and etc.

# Group names in brackets, Domain controllers, Windows Servers.
[domain_controllers]
# Add domain controller hosts (Change once either made on OpenStack or through Terraform)
dc01 ansible_host = 1.1.1.1

[windows:children]
domain_controllers

# Variables for all windows servers in the inventory
[windows:vars]
ansible_user = Administrator
ansible_password = bleh
ansible_connection = winrm
ansible_winrm_transport = ntlm
ansible_winrm_server_cert_validation = ignore
ansible_port = 5986

# Password authentication instead of SSH Key
ansible_ssh_pass = {{ ansible_password }}

# Location of python on remote server
ansible_python_interpreter = /usr/bin/python3

# Connect through CyberRange jump host
ansible_ssh_common_args = -o ProxyJump=sshjump@ssh.cyberrange.rit.edu -o StrictHostKeyChecking=no

