# Ansible Hosts File For SCP Echo Grey Team
# This file will specify the hosts that Ansible will manage for the following Windows Servers
# Domain controller, SMB server, SFTP Server

[domain_controllers]
scp_dc01 ansible_host=1.1.1.1

[smb_servers]
scp_smb01 ansible_host=1.1.1.2

[sftp_servers]
scp_sftp01 ansible_host=1.1.1.3

[windows:children]
domain_controllers
smb_servers
sftp_servers

# Variables for all windows servers in the inventory/hosts.ini
[windows:vars]
ansible_user = cyberrange
ansible_password = student
ansible_connection = winrm
ansible_winrm_transport = ntlm
ansible_winrm_server_cert_validation = ignore
ansible_port = 5986

# Password authentication instead of SSH Key
ansible_ssh_pass = {{ ansible_password }}

# Location of python on remote server
ansible_python_interpreter = /usr/bin/python3

# Connect through CyberRange jump host
ansible_ssh_common_args = -o ProxyJump=sshjump@ssh.cyberrange.rit.edu -o StrictHostKeyChecking=no
