---
# ====================================================
# Active Directory Configuration Variables
# Used by: playbooks/setup-ad.yml -> roles/dc
# ====================================================

domain_name: "scp.com"
domain_netbios_name: "SCP"
safe_mode_password: "DONOTTOUCH!!!@123$"
forest_mode: "WinThreshold"
domain_mode: "WinThreshold"

forward_zone: "scp.com"
reverse_zone: "10.10.10.in-addr.arpa"

dc_hostname: "SCP-DC01"
dc_ip_address: "10.10.10.21"

# Network Configuration
dns_forwarder: "8.8.8.8"

# Organizational Units
organizational_units:
  - name: "Servers"
    path: "OU=Servers,DC=scp,DC=com"
  - name: "Service Accounts"
    path: "OU=Service Accounts,DC=scp,DC=com"

# Create domain users
domain_users:
  - username: "overseer.scp"
    password: "weakpassword123!"
    firstname: "Overseer"
    lastname: "SCP"
    ou: "CN=Users,DC=scp,DC=com"
    groups:
      - "Domain Admins"
  - username: "GREYTEAM"
    password: "DONOTTOUCH!!!"
    firstname: "GREY"
    lastname: "TEAM"
    ou: "CN=Users,DC=scp,DC=com"
    groups:
      - "Domain Admins"
  - username: "AD-Admin"
    password: "533431"
    firstname: "AD"
    lastname: "Admin"
    ou: "CN=Users,DC=scp,DC=com"
    groups:
      - "Domain Admins" 
  - username: "umadan"
    password: "Test321!"
    firstname: "Uma"
    lastname: "Dan"
    ou: "CN=Users,DC=scp,DC=com"
